#!/usr/bin/env bash

## Prepares theme for local development.
##
## Usage: fin develop-theme

# Abort if anything fails
set -e

#-------------------------- Execution Steps --------------------------------

# Runs webpack and storybook dev watch task.
fin exec "cd /var/www/web/themes/custom/motional && npm run develop"
